---

- name: "httpd-alias: Configure aliases in {{ apache_conf_path }}/httpd.conf"
  ansible.builtin.blockinfile:
    dest: "{{ apache_conf_path }}/httpd.conf"
    insertafter: "<IfModule alias_module>"
    block: |2
        {% for item in apache_alias %}
        {{ item }}
        {% endfor %}
    backup: "{{ apache_backup_conf }}"
  notify: reload apache
  when: apache_alias|length > 0

# EOF
...
